### ISSUE TITLE
Tab to be opened as close to the right as possible.

### ISSUE THREAD

**Issue by michaelcadilhac** [jaden/Tab-Position-Customizer-2#1]
Hi there;

Thanks for your work on this, very appreciated.  I have a simple feature request here.  When I hit C-t, I like the new tab to be just next the current one; this correctly fails if I'm on a pinned tab.  The fallback here is for the new tab to be put at the end, while I'd have preferred it to be put as the first unpinned tab.  This is closer to Firefox's approach, by the way.

If you're not willing to have that as the default behavior, would you mind helping me implement this?  I tried wrapping lines 65:92 with:

```
	chrome.windows.get(windowId, {"populate": true}, function (window)
	{
		for(var i = 0; i < window.tabs.length; i++) {
			var tab = window.tabs[i];
			if(!tab.pinned) {
				break;
			}
		}
		index = Math.max(index, i);
		...
	}});
```
but this somehow fails (I'm probably showing off my complete lack of understanding of Chromisms here.)

Cheers!

**Comment by jaden** [comment]
I actually didn't write this, I just pulled out the advertising code that the new owner had added and created a new extension.

**Comment by michaelcadilhac** [comment]
How does that prevent us from trying to improve the design?  As far as I can see, this version of the extension is quite popular on the official chrome repository, so that'd be for the better good.

**Comment by jaden** [comment]
It doesn't prevent it in the least. I gladly accept pull requests :)

**Comment by michaelcadilhac** [comment]
Great!  Would you mind helping me then?  I do not know why the above approach does not work, for instance.  Cheers!

**Comment by jaden** [comment]
Therein lies the rub. I don't have time to work on this. If you can figure it out, I'm willing to add the feature.
