### ISSUE TITLE
Tab Customizer 2 causes problems with Google Hangouts extension (Mac)

### ISSUE THREAD

**Issue by szczykafka** [jaden/Tab-Position-Customizer-2#2]
Definitely problems caused by Tab Customizer 2.
Screen recording which shows the issue: [LINK](https://www.dropbox.com/s/n65w7kkasrbr8d7/Google-Chrome-Extention-Tab-Customizer-2-causes-problems.mov?dl=0)

Any suggestions?

**Comment by jaden** [comment]
I'm not actively using this extension anymore so I don't have any suggestions to resolve this. If you're able to submit a PR with a fix, I'd happy to incorporate any changes.
