### ISSUE TITLE
"Right of current tab" disfunction in the latest chrome version -(Version 91.0.4472.77 (Official Build) (64-bit))

### ISSUE THREAD

**Issue by bravo-hero** [jaden/Tab-Position-Customizer-2#3]
Hi Team,
   this function well all along the way, until yesterday i updated the chrome to be the latest version.
   so today i noticed it can't funtion as expected, i've tried restart the chrome, at first, it seems to be normal back, but when the tabs become more(around 40 ones), i then noticed again it's out of function.

pls take a check if there's a bug.

thanks.

**Comment by noe132** [comment]
when opening new tab, sometime the new tab is at left of current tab, sometimes right, and sometimes at the end.
using chrome 91.0.4472.77 on windows 10

**Comment by ZeaeD** [comment]
Hi guys,

the ext has stopped working with 91.0.4472.77 Win7 x64 :(

**Comment by jaden** [comment]
Thanks to @farazoman's PR this should be fixed once the extension gets through the review process.

**Comment by bravo-hero** [comment]
it feels better, but, it still got the similar issue. not 1 time, not 2 time, but several times already.
it's kind of the process: 

long time no use the chrome window, then tabs-> got freezing(i guess)->at one time i come back to create a new tab->
IT CREATED IN THE RIGHTEST OF THE CHROME AS THE DEFAULT BEHAVIOR->i noticed the issue, i create a new tab one more time->it created in the right as the current active tab(as expected)->this issue urge me to come back to report this issue back.

thanks.
