### ISSUE TITLE
Plugin usage issues in newer versions of chrome

### ISSUE THREAD

**Issue by youland** [jaden/Tab-Position-Customizer-2#6]
Google Chrome version  91.0.4472.124（64bit) and update at today( 8 July 2021 )
----Open new tab
Opening a new tab is ok,It is to the left of the current tab

----Close tab
When closing tabs, sometimes the left tab is activated, sometimes not

Can you update the source code? We download the package ourselves and install it from developer mode

Thanks.

**Comment by jaden** [comment]
I'm no longer maintaining this extension. Please see https://github.com/jaden/Tab-Position-Customizer-2#readme
