### ISSUE TITLE
Malware in the extension?

### ISSUE THREAD

**Issue by chrcoluk** [jaden/Tab-Position-Customizer-2#8]
This just got auto disabled in my browser because it has malware in it, can the dev give an explanation please.

**Comment by ffplayer** [comment]
It was already explained at the homepage. 

> Tab Position Customizer 2 (no longer available in Chrome appstore)
Update: I removed the extension from the web store after Google rejected the updates and threatened to suspend my account. I no longer even use this extension and it's become too much of a hassle and certainly not worth losing access to my account. If someone else would like to continue maintaining it, feel free to reach out.

>Chrome extension to customize tab opening position and closing behavior.

>Based on the Tab Position Customizer extension. I changed the name, the icon and removed some code that was accessing Google Analytics. I left the other language files alone. If you speak one of those languages, send me an update.


Now you can install it in this way:
> Or you can download the code, enable developer mode on the Chrome extensions page and add it with "Load unpacked extension".
