### ISSUE TITLE
Upload last version crx file to GitHub?

### ISSUE THREAD

**Issue by tomasz1986** [jaden/Tab-Position-Customizer-2#9]
Would you mind uploading the `crx` file of the last version to GitHub for preservation purposes? The advantage of using `crx` instead of an unpacked folder is that the former will be added to Chromium and remain there even after deleting the original `crx` file, while with the latter, if you delete or change the unpacked extension path, it will stop working in the browser too.

I know that there are ways to create a `crx` archive from an unpacked extension manually, but having a file ready to download and simply drag and drop into the browser is just more convenient 😉.

**Comment by jaden** [comment]
Done.
